name = "fast-translation-webapp"
main = "main.py"
compatibility_date = "2024-01-15"
compatibility_flags = ["python_workers"]

[env.production.vars]
# Environment variables will be set via wrangler secret put command
# GEMINI_API_KEY = "your-api-key-here"
# PROJECT_ID = "534521643480"
# LOCATION = "us-central1"
# GOOGLE_CLOUD_MODEL = "projects/534521643480/locations/us-central1/models/NM3ad0dd20ffa743ba"